# **2. Numpy exercises**

1. Import the numpy package under the name `np`

`hint: import … as`

In [1]:
import numpy as np

2. Create a null vector of size 10

`hint: np.zeros`



In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 0 to 100

`hint: arange`

In [4]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

4. Create a 10x10 matrix with random values and find the minimum, maximum, and mean values. Normalize the said matrix 

`hint: min, max, ...`

In [8]:
a = np.random.rand(10,10)
print('minimum: \t',a.min(),'\nmaximum: \t',a.max(),'\nmean: \t\t',a.mean())

minimum: 	 0.007995257400943645 
maximum: 	 0.9778887047814986 
mean: 		 0.48905633666454196


5. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

`hint: np.sqrt, np.arctan2`

In [42]:
np.random.seed(10)
cart = np.random.randint(0,10,(10,2))
polar = np.zeros((10,2))
polar[:,0] = np.sqrt(cart[:,0]^2 + cart[:,1]^2)
polar[:,1] = np.arctan2(cart[:,1],cart[:,0])
polar

array([[3.60555128, 0.41822433],
       [1.        , 1.57079633],
       [3.        , 0.        ],
       [3.        , 1.44644133],
       [3.        , 0.        ],
       [1.41421356, 0.64350111],
       [1.73205081, 0.64350111],
       [2.        , 1.57079633],
       [3.74165739, 0.92729522],
       [3.        , 1.44644133]])

6. Create random vector of size 10 and replace the maximum value by 0

`hint: argmax`

In [41]:
b = np.random.randint(1,11,10)
print(b)
b[b.argmax()] = 0
print(b)

[1 1 8 1 6 3 8 4 2 8]
[1 1 0 1 6 3 8 4 2 8]


7. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

`hint: np.meshgrid`

In [44]:
x = np.arange(0, 1.1, 0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [54]:
np.meshgrid(x,x)

[array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
        [0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]]),
 array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
        [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
        [0.4, 0.4, 0.4,

8. Having a scalar `x` and a random vector `v`, find a value in `v` that is closest to `x`

`hint: argmin`

In [65]:
np.random.seed(14)
x = np.random.randint(1,11,1)
v = np.random.rand(10) * 10
closest = abs(v - x).argmin()
print(v)
print(v[closest],' is the entry closest to ',x[0])

[7.73165052 8.70427686 0.08046949 3.09735926 9.57603739 5.13116712
 3.18284425 5.39199937 2.21254942 8.06481358]
8.704276857248127  is the entry closest to  9


9. Consider a random vector with shape (100,2) representing coordinates, find point by point distances and put them in a (100,100) array.

In [67]:
coords = np.random.randint(0,11,(100,2))

In [77]:
dists = np.zeros((100,100))
for i in range(100):
    for j in range(100):
        c1 = coords[i,:]
        c2 = coords[j,:]
        try:
            dists[i,j] = np.sqrt((c2[0]-c1[0])^2 + (c2[1]-c1[1])^2)
        except:
            dists[i,j] = 0
dists

C:\Users\jonas\AppData\Local\Temp\ipykernel_8896\1344153620.py:7: RuntimeWarning: invalid value encountered in sqrt
  dists[i,j] = np.sqrt((c2[0]-c1[0])^2 + (c2[1]-c1[1])^2)


array([[0.        , 1.        ,        nan, ..., 2.        , 1.73205081,
        3.74165739],
       [       nan, 0.        ,        nan, ...,        nan,        nan,
        1.        ],
       [       nan, 2.23606798, 0.        , ...,        nan,        nan,
        2.        ],
       ...,
       [       nan, 1.73205081,        nan, ..., 0.        ,        nan,
        1.41421356],
       [       nan, 2.        ,        nan, ..., 1.73205081, 0.        ,
        2.64575131],
       [       nan,        nan, 0.        , ...,        nan,        nan,
        0.        ]])

10. Create a random (100, 100) matrix with values from 0 to 1. Turn all values lower than 0.5 into 0.0

In [85]:
hundred = np.random.rand(100,100)
hundred[hundred[:,:] < 0.5] = 0

array([[0.72279696, 0.73140917, 0.        , ..., 0.88475388, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.52154884, 0.86590074, 0.        , ..., 0.        , 0.95624389,
        0.55071677],
       ...,
       [0.        , 0.94751214, 0.92295234, ..., 0.87414766, 0.83343977,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.66685507],
       [0.53696382, 0.        , 0.67796111, ..., 0.64720146, 0.61963185,
        0.67879746]])

11. Sort an array by the nth column.

In [93]:
def sort_by_random(array):
    n = np.random.randint(0,len(array))
    print('Sort by column ',n)
    return array[array[:,n].argsort()]

In [94]:
sort_by_random(hundred)

Sort by column  99


array([[0.72279696, 0.73140917, 0.        , ..., 0.88475388, 0.        ,
        0.        ],
       [0.87894768, 0.60605082, 0.50347783, ..., 0.5062815 , 0.        ,
        0.        ],
       [0.        , 0.        , 0.76368949, ..., 0.65534792, 0.83762145,
        0.        ],
       ...,
       [0.50185979, 0.9499529 , 0.93476826, ..., 0.99074215, 0.86463893,
        0.96974117],
       [0.57806169, 0.62741185, 0.94753915, ..., 0.70177033, 0.88765327,
        0.97504505],
       [0.82279406, 0.        , 0.        , ..., 0.97030083, 0.        ,
        0.97844561]])

12. Subtract the mean of each row of a matrix.

In [115]:
a = np.random.randint(0,11,(5,5))
for i in range(len(a)):
    b[i] = a[i] - np.mean(a[i])
print(a)
print(b)

[[ 6  2  8  8 10]
 [ 9  3  8  5  9]
 [ 7  3  7  4  1]
 [ 0  3  0  5  9]
 [ 7  6  9  3  8]]
[[-0.8 -4.8  1.2  1.2  3.2]
 [ 2.2 -3.8  1.2 -1.8  2.2]
 [ 2.6 -1.4  2.6 -0.4 -3.4]
 [-3.4 -0.4 -3.4  1.6  5.6]
 [ 0.4 -0.6  2.4 -3.6  1.4]]


13. Do a dot product of two matrices and print only the diagonal values.

In [100]:
a = np.random.rand(5,5)
b = np.random.rand(5,5)
c = np.dot(a,b)
for i in range(len(c)):
    print(c[i][i])

1.5295583587793637
0.6666267334805988
1.536171377666133
1.3736429546482911
1.90341137141635


14. Swap two rows of a matrix.

In [106]:
a = np.random.rand(5,5)
def swap(array,i,j):
    old = array.copy()
    array[i], array[j] = old[j], old[i]
    return array
print(a)
print(swap(a,0,1))

[[0.45725073 0.77610919 0.2149972  0.45879591 0.9029144 ]
 [0.02784528 0.20191782 0.47429469 0.10376212 0.98617141]
 [0.24099708 0.72687676 0.67254424 0.54075033 0.32697288]
 [0.2540496  0.09098764 0.27721074 0.06604909 0.0228498 ]
 [0.88045262 0.92926189 0.63273994 0.5503846  0.95067369]]
[[0.02784528 0.20191782 0.47429469 0.10376212 0.98617141]
 [0.45725073 0.77610919 0.2149972  0.45879591 0.9029144 ]
 [0.24099708 0.72687676 0.67254424 0.54075033 0.32697288]
 [0.2540496  0.09098764 0.27721074 0.06604909 0.0228498 ]
 [0.88045262 0.92926189 0.63273994 0.5503846  0.95067369]]


15. find the most frequent value in an array

In [113]:
a = np.random.randint(0,11,(5,5))
uniq = np.unique(a,return_counts=True)
print('Most frequent entry in array is')
uniq[0][uniq[1].argmax()]

Most frequent entry in array is


6